name: Publish data models snapshots

on:
  push:
    branches:
      - 'main'
    paths:
      - 'data-models/**'

jobs:
  jargon_snapshot:
    uses: uncefact/.github/.github/workflows/untp-data-models-publish.yml@main
    secrets: inherit
    with:
      version: "working"
      comment: "Update working version"
