name: Publish data models snapshots

on:
  push:
    branches:
      - 'data-models-staging'
    paths:
      - 'data-models/**'

jobs:
  jargon_snapshot:
    uses: uncefact/.github/.github/workflows/untp-data-models-snapshot.yml@main
    secrets: inherit