name: Docs-to-PDF check

on:
  push:
    branches:
      - main
    paths-ignore:
      - "website/static/un-transparency-protocol.pdf"

jobs:
  check:
    uses: ./.github/workflows/docs-to-pdf.yml
    secrets: inherit
